config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  
  devise_for :users
  root "products#home"
  resources :products 
  resources :wishlists
  resources :order_items

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
    end

    private

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end
  
  def total
    return unit_price*quantity
  end

  private
  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total*quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper   
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
#frozen_string_litral: true
class OrderItemsController < ApplicationController
    before_action :set_order
    def create
      @order_item = @order.order_items.new(order_params)
      @order.save
      session[:order_id] = @order.id
    end
  
    def update
      @order_item = @order.order_items.find(params[:id])
      @order_item.update(order_params)
      @order_items = current_order.order_items
    end
  
    def destroy
      @order_item = @order.order_items.find(params[:id])
      @order_item.destroy
      @order_items = current_order.order_items
    end
  
    private
    def order_params
      params.require(:order_item).permit(:product_id,:user_id, :quantity)
    end
  
    def set_order
      @order = current_order
    end
  
end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  layout 'navbar' 
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def new 
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.valid?
      redirect_to products_path
    else
      flash[:errors] = @product.errors.full_messages
      redirect_to new_product_path
    end

  end

  def show  
  end

  def edit 
  end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def index
  end

  def new
  end

  def create
    
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
        if Order.find_by_id(session[:order_id]).nil?
          Order.new
        else
          Order.find_by_id(session[:order_id])
        end
    end  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/cart/_cart_items.html.erb
<%= @order_items.each do |item|%>
  <h3><%= item.product.name%></h3>
  <h3><%= item.product.price%></h3>
  <%= form_with model: item do |f|%>
    <%= f.hidden_field :product_id, value: item.product.id %>
    <%= f.number_field :quantity, value: item.quantity.to_i%>
    <%= f.submit"Update Cart"%>
    <%= button_to "Remove Item", order_item_path(item), method: :delete%>
  <%end%>
<%end%>
<h3>Your current order has a total of: <%= current_order.subtotal %></h3>

app/views/cart/cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/show.html.erb
<div id="cart-item">
    <%= render 'cart_items'%>
</div>

app/views/layouts/admin.html.erb
<html>
  <body>
    <%= yield %>
    <p>Hello the is from layout</p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practical1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/layouts/navbar.html.erb
<html>
  <head>
    <%= yield %>
    <table>
        <%if current_user%>
        <tr>
        <p><%= button_to "Log out", destroy_user_session_path,method: :delete%></p>  
        </tr>  
        <%else%>
        <tr>
            <p><%= link_to "Log in", new_user_session_path%></p>
        </tr>
        <tr>
            <p><%= link_to "sign up", new_user_registration_path%></p>
        </tr>
        <%end%>

    </table>
  </head>
</html>

app/views/oder_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>)");

app/views/oder_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/oder_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/products/_form.html.erb
<%= form_with(model: @product, local:true) do |form| %>
    <% if @product.errors.any? %>
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
  
        <ul>
          <% @product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
    <% end %>
      <%= form.label :name %>
      <%= form.text_field :name %>

      <%= form.label :description %>
      <%= form.text_field :description %>


      <%= form.label :price %>
      <%= form.number_field :price %>

      <%= form.submit %>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<%= render 'form' %>

app/views/products/home.html.erb
<%if current_user%>
  <p><%= button_to "Log out", destroy_user_session_path,method: :delete%></p>    
  <%= button_to "Vew Products",products_path,method: :get %>  
<%else%>
  <p><%= link_to "Log in", new_user_session_path%></p>
  <p><%= link_to "sign up", new_user_registration_path%></p>
<%end%>

app/views/products/index.html.erb
<h1>Products#index</h1>
<table border = "2px">
    <tr><center>Products Details </center></tr>
    <tr>
      <td>Name</td><td>Description</td><td>Price</td><td>Show</td>
      <%if current_user.admin? %>
        <td>Edit</td><td>Delete</td>
      <%end%>
    </tr>
    <% @products.each do |s| %>
      <tr>
        <td><%=s.name %></td>
        <td><%=s.description%></td>
        <td><%=s.price %></td>
        <td><%= button_to 'Show', product_path(s), method: :get%></td>
        <td>
          <%= form_with model: @order_item,  remote: true do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :product_id, value: s.id%>
            <%= f.number_field :quantity, value:1, min: 1%>
            <%= f.submit "Add To Cart"%>
          <%end%>
        </td>  
        <% if current_user.admin? %>
          <td><%= button_to 'Edit', edit_product_path(s), method: :get%></td>
          <td><%= button_to 'Remove', product_path(s), method: :delete%></td>  
        <%end%>
      </tr>
    <% end %>
  </table>

<%= button_to "Add New Product", new_product_path, method: :get%>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<h1><%= @product.name%>'s page</h1>

<h2>Description: <%=@product.description%></h2>
<h3>Price: <%=@product.price%></h3>
<% if current_user.admin? %>
  <%= button_to "Edit Product", edit_product_path, method: :get%>
  <%= button_to "Destroy Product",product_path,method: :delete%>
<%end%>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/wishlists/create.html.erb
<h1>Wishlists#create</h1>
<p>Find me in app/views/wishlists/create.html.erb</p>

app/views/wishlists/destroy.html.erb
<h1>Wishlists#destroy</h1>
<p>Find me in app/views/wishlists/destroy.html.erb</p>

app/views/wishlists/edit.html.erb
<h1>Wishlists#edit</h1>
<p>Find me in app/views/wishlists/edit.html.erb</p>

app/views/wishlists/index.html.erb
<h1>Wishlists#index</h1>
<p>Find me in app/views/wishlists/index.html.erb</p>

app/views/wishlists/new.html.erb
<h1>Wishlists#new</h1>
<p>Find me in app/views/wishlists/new.html.erb</p>

app/views/wishlists/show.html.erb
<h1>Wishlists#show</h1>
<p>Find me in app/views/wishlists/show.html.erb</p>

app/views/wishlists/update.html.erb
<h1>Wishlists#update</h1>
<p>Find me in app/views/wishlists/update.html.erb</p>